// Generated by CoffeeScript 1.7.1
(function() {
  var box, display;

  display = function(colors) {
    var html;
    html = colors.map(function(color) {
      var h, l, s;
      if (color == null) {
        color = [0, 0, 100];
      }
      h = color[0], s = color[1], l = color[2];
      return "<div class='color' style='background: hsl(" + h + ", " + s + "%, " + l + "%)'></div>";
    });
    html = "<div class='colors'>" + (html.join('')) + "</div>";
    return document.getElementById("colors").innerHTML = html;
  };

  box = document.getElementById("image");

  box.ondragover = function(event) {
    this.className = 'hover';
    return event.preventDefault();
  };

  box.ondragend = function(event) {
    this.className = '';
    return event.preventDefault();
  };

  box.ondrop = function(event) {
    var file, reader;
    box.innerHTML = "";
    document.getElementById("colors").innerHTML = "Calculating...";
    event.preventDefault();
    file = event.dataTransfer.files[0];
    reader = new FileReader;
    reader.onload = function(event) {
      var dataURL;
      dataURL = event.target.result;
      clustering({
        maxWidth: 100,
        maxHeight: 100,
        url: dataURL,
        debug: false
      }, function(centers) {
        return display(centers);
      });
      return box.style.backgroundImage = "url(" + dataURL + ")";
    };
    return reader.readAsDataURL(file);
  };

}).call(this);
