// Generated by CoffeeScript 1.7.1
(function() {
  var box;

  box = document.getElementById("image");

  box.ondragover = function(event) {
    this.className = 'hover';
    return event.preventDefault();
  };

  box.ondragend = function(event) {
    this.className = '';
    return event.preventDefault();
  };

  box.ondrop = function(event) {
    var file, reader;
    event.preventDefault();
    file = event.dataTransfer.files[0];
    reader = new FileReader;
    reader.onload = function(event) {
      var dataURL, image;
      dataURL = event.target.result;
      clustering({
        maxWidth: 100,
        maxHeight: 100,
        url: dataURL,
        debug: false
      }, function(centers) {
        return console.log(centers);
      });
      image = new Image;
      image.src = dataURL;
      image.width = 400;
      return document.body.appendChild(image);
    };
    return reader.readAsDataURL(file);
  };

}).call(this);
