// Generated by CoffeeScript 1.7.1
(function() {
  var clustering;

  clustering = function(points) {
    var clusterCount;
    clusterCount = 16;
    return null;
  };

  window.clustering = clustering;

}).call(this);
