// Generated by CoffeeScript 1.7.1
(function() {
  var clustering, distance, hypot,
    __slice = [].slice;

  if (Math.hypot != null) {
    hypot = Math.hypot;
  } else {
    hypot = function() {
      var args, sum;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      sum = 0;
      sum = args.forEach(function(val) {
        return sum += val;
      });
      return Math.sqrt(sum);
    };
  }

  distance = function(p1, p2) {
    var delta;
    delta = p1.map(function(val, i) {
      return val - p2[i];
    });
    return hypot.apply(delta);
  };

  clustering = function(points) {
    var clusters, h, n, point, s, v, _i, _len, _results;
    n = 16;
    clusters = [];
    _results = [];
    for (_i = 0, _len = points.length; _i < _len; _i++) {
      point = points[_i];
      h = point[0], s = point[1], v = point[2];
      s *= 100;
      _results.push(v *= 100);
    }
    return _results;
  };

  window.clustering = clustering;

}).call(this);
