// Generated by CoffeeScript 1.7.1
(function() {
  var rgb2hsl;

  rgb2hsl = function(r, g, b) {
    var h, l, max, min, s, _ref, _ref1;
    _ref = [r, g, b].map(function(elem) {
      return elem / 255;
    }), r = _ref[0], g = _ref[1], b = _ref[2];
    max = Math.max(r, g, b);
    min = Math.min(r, g, b);
    if (max === min) {
      h = 0;
    } else if (max === r && g >= b) {
      h = 60 * (g - b) / (max - min);
    } else if (max === r && g < b) {
      h = 60 * (g - b) / (max - min) + 360;
    } else if (max === g) {
      h = 60 * (b - r) / (max - min) + 120;
    } else {
      h = 60 * (r - g) / (max - min) + 240;
    }
    l = (max + min) / 2;
    if (max === min || l === 0) {
      s = 0;
    } else if (l > 0 && l <= 0.5) {
      s = (max - min) / (max + min);
    } else {
      s = (max - min) / (2 - (max + min));
    }
    h = parseInt(h);
    _ref1 = [s, l].map(function(elem) {
      return Math.round(elem * 100) / 100;
    }), s = _ref1[0], l = _ref1[1];
    return [h, s, l];
  };

  window.rgb2hsl = rgb2hsl;

}).call(this);
