// Generated by CoffeeScript 1.7.1
(function() {
  var ctx, img, url;

  ctx = document.getElementById("canvas").getContext("2d");

  url = "test.min.jpg";

  img = new Image();

  img.onload = function() {
    var b, g, h, i, image, imgData, points, r, scale, w, _ref, _ref1;
    image = this;
    scale = 2.5;
    _ref = [image.width, image.height].map(function(elem) {
      return parseInt(elem / scale);
    }), w = _ref[0], h = _ref[1];
    console.log({
      w: w,
      h: h
    });
    canvas.style.width = "" + w + "px";
    canvas.style.height = "" + h + "px";
    ctx.drawImage(this, 0, 0, image.width, image.height, 0, 0, w, h);
    imgData = ctx.getImageData(0, 0, w, h);
    points = [];
    i = 0;
    while (i < imgData.data.length) {
      _ref1 = [imgData.data[i], imgData.data[i + 1], imgData.data[i + 2]], r = _ref1[0], g = _ref1[1], b = _ref1[2];
      points.push(window.rgb2hsl(r, g, b));
      i += 4;
    }
    console.log(points.length);
    return window.clustering(points);
  };

  img.src = url;

}).call(this);
