// Generated by CoffeeScript 1.7.1
(function() {
  var $, body, colorsClustering, display;

  body = document.body;

  body.ondrop = function(event) {
    var box, config, img, url;
    event.preventDefault();
    box = document.getElementById("image");
    url = URL.createObjectURL(event.dataTransfer.files[0]);



    config = {
      src: url,
      minCount: 7
    };
    colorsClustering(config, function(clusters) {
      var C, colorMatchings, html, schemes;

      colorMatchings = [];

      schemes = C([0, 1, 2, 3, 4, 5, 6], 5).map(function(scheme) {
        return scheme.map(function(i) {
          return clusters[i].color;
        });
      });
      html = schemes.map(function(colors) {
        var tmp;
        tmp = colors.map(function(color) {
          return "<div class='color' style='background: rgb(" + (color.join(',')) + ")'></div>";
        });
        return "<div class='scheme' data-scheme='" + (JSON.stringify(colors)) + "'>" + (tmp.join('')) + " <i class='fa fa-heart-o button'></i> <i class='fa fa-trash-o button'></i></div>";
      });
      document.getElementById("schemes").innerHTML = html.join('');
      return (function() {
        var getScore, setScore;
        getScore = function($scheme) {
          if ($scheme.find('.fa-heart-o').hasClass('selected')) {
            return 1;
          } else if ($scheme.find('.fa-trash-o').hasClass('selected')) {
            return -1;
          } else {
            return 0;
          }
        };
        setScore = function($scheme, score) {
          var data, error, password, success, username;
          $scheme.find('.fa-heart-o').toggleClass('selected', score > 0);
          $scheme.find('.fa-trash-o').toggleClass('selected', score < 0);
          url = "http://jp.zenozeng.com:26080";
          username = localStorage.getItem('username');
          password = localStorage.getItem('password');
          data = {
            scheme: JSON.stringify($scheme.data('scheme')),
            score: score,
            username: username,
            password: password
          };
          console.log(data);
          success = function(data) {
            return console.log(data);
          };
          error = function() {
            return alert('服务器貌似坏了，告诉zeno吧');
          };
          return $.ajax({
            url: url,
            data: data,
            success: success,
            error: error
          });
        };
        $('.scheme .fa-heart-o').click(function() {
          var $scheme;
          $scheme = $(this).parents('.scheme');
          if (getScore($scheme) === 1) {
            return setScore($scheme, 0);
          } else {
            return setScore($scheme, 1);
          }
        });
        return $('.scheme .fa-trash-o').click(function() {
          var $scheme;
          $scheme = $(this).parents('.scheme');
          if (getScore($scheme) === -1) {
            return setScore($scheme, 0);
          } else {
            setScore($scheme, -1);
            return $scheme.appendTo($('#schemes'));
          }
        });
      })();
    });

  };

}).call(this);
